version: "3"
services:
  web:
    build: .
    ports:
        - 8080:8080
    environment:
        - OTEL_TRACES_EXPORTER=jaeger
        - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250
        - OTEL_EXPORTER_JAEGER_TIMEOUT=10000
        - OTEL_LOG_LEVEL=debug
  jaeger:
    image: jaegertracing/all-in-one:1.24
    ports:
        - 16686:16686