receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680

exporters:
  otlp/2:
    endpoint: data-prepper:21890
    tls:
      insecure: true
      insecure_skip_verify: true
  logging:
  kafka:
    brokers:
      - kafka:9092
    topic: apm
    protocol_version: 2.8.0

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [kafka]