receivers:
  kafka:
    brokers:
      - kafka:9092
    topic: apm
    protocol_version: 2.8.0
exporters:
  otlp/2:
    endpoint: data-prepper:21890
    tls:
      insecure: true
      insecure_skip_verify: true
  logging:

service:
  pipelines:
    traces:
      receivers: [kafka]
      exporters: [otlp/2, logging]